name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy frontend via docker-compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} '
            rm -rf ~/deploy_temp_frontend &&
            mkdir ~/deploy_temp_frontend
          '

          scp -r ./* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/deploy_temp_frontend

          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} '
            rsync -av ~/deploy_temp_frontend/ /root/projects/KarateCoaching/frontend/ &&
            cd /root/projects/KarateCoaching/frontend &&
            docker compose down &&
            docker compose up -d --build &&
            rm -rf ~/deploy_temp_frontend
          '
